Readme
stepa1000/echo-bot-template pull request #26
Opened 2023-02-28 10:02 UTC by stepa1000

2023-02-28 10:38 UTC, pavelzarubin requested changes
https://coda.io/@metalamp/education/3-14

еще раз прочитай

2023-03-07 08:40 UTC, pavelzarubin commented
1. Нужна полная пошаговая инструкция по запуску. Ссылка на описание `stack`, сборка проекта и запуск.
2. Описание конфига.
3. Описание структуры должно быть полное, за что каждый из модулей отвечает.
4. Описание самой программы, ее полный функционал.
Если сложно с английским используй  deepl. Ну и базовая пунктуация и грамматика должны быть (точки, запятые, заглавные буквы).
Ну и используй markdown активнее.

2023-03-16 08:28 UTC, pavelzarubin approved these changes

2023-03-16 08:28 UTC, pavelzarubin commented on .README.md.swo
добавь расширения этих файлов в .gitignore

2023-03-20 07:47 UTC, stepa1000 commented
мержитиь?

2023-03-20 07:57 UTC, pavelzarubin commented
апрув стоит значит мерджить

2023-03-20 15:03 UTC, merged